/**
 * Database schema (Drizzle / Postgres).
 *
 * Notes:
 *  - All primary keys are UUIDs generated by Postgres (gen_random_uuid()).
 *  - All money fields are `numeric(12, 2)` and round-tripped as strings via Drizzle.
 *  - `userId` references Supabase Auth's `auth.users.id` (managed externally; we do not redeclare it).
 *  - Soft delete via `deletedAt`; a daily cleanup task hard-deletes 30-day-old rows (to be wired in step 4 of BUILD-PLAN).
 */

import {
  pgTable,
  uuid,
  text,
  timestamp,
  numeric,
  boolean,
  integer,
  pgEnum,
  index,
  uniqueIndex,
  jsonb,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const platformEnum = pgEnum('platform', ['EBAY', 'DEPOP', 'VINTED', 'OTHER']);
export const itemStatusEnum = pgEnum('item_status', [
  'DRAFT',
  'IN_STOCK',
  'LISTED',
  'SOLD',
  'RETURNED',
  'DELISTED',
]);
export const transactionKindEnum = pgEnum('transaction_kind', [
  'SALE',
  'REFUND',
  'FEE',
  'SHIPPING_LABEL',
  'OTHER',
]);
export const transactionSourceEnum = pgEnum('transaction_source', ['CSV', 'API', 'MANUAL']);
export const connectionModeEnum = pgEnum('connection_mode', ['API', 'MANUAL']);
export const expenseCategoryEnum = pgEnum('expense_category', [
  'MILEAGE',
  'PACKAGING',
  'SUBSCRIPTION',
  'OFFICE',
  'OTHER',
]);
export const taxYearStatusEnum = pgEnum('tax_year_status', ['OPEN', 'SUBMITTED', 'LOCKED']);
export const jurisdictionEnum = pgEnum('jurisdiction', ['EW_NI', 'SCOTLAND']);

// ---------------------------------------------------------------------------
// profiles — augments Supabase auth.users with our app-level user data
// ---------------------------------------------------------------------------

export const profiles = pgTable('profiles', {
  /** Same UUID as auth.users.id; we mirror it here for FK convenience. */
  id: uuid('id').primaryKey(),
  email: text('email').notNull(),
  name: text('name'),
  avatarUrl: text('avatar_url'),
  timezone: text('timezone').notNull().default('Europe/London'),
  currency: text('currency').notNull().default('GBP'),
  jurisdiction: jurisdictionEnum('jurisdiction').notNull().default('EW_NI'),
  studentLoanPlan: text('student_loan_plan').notNull().default('NONE'),
  // Optional inputs to the tax engine
  payeIncomeAnnual: numeric('paye_income_annual', { precision: 12, scale: 2 }),
  // House-keeping
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// platform_connections
// ---------------------------------------------------------------------------

export const platformConnections = pgTable(
  'platform_connections',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull(),
    platform: platformEnum('platform').notNull(),
    mode: connectionModeEnum('mode').notNull().default('MANUAL'),
    /** Encrypted at app layer with AES-256-GCM. Format: ivBase64:tagBase64:cipherBase64. */
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }),
    scopes: text('scopes'),
    ebayUserId: text('ebay_user_id'),
    // Per-user fee overrides (JSON, falls back to platform defaults)
    feeOverrides: jsonb('fee_overrides'),
    lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
    lastSyncStatus: text('last_sync_status'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userPlatformUnique: uniqueIndex('platform_connections_user_platform').on(t.userId, t.platform),
  }),
);

// ---------------------------------------------------------------------------
// items
// ---------------------------------------------------------------------------

export const items = pgTable(
  'items',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull(),
    sku: text('sku'),
    title: text('title').notNull(),
    description: text('description'),
    brand: text('brand'),
    category: text('category'),
    size: text('size'),
    condition: text('condition'),
    // Sourcing
    sourcePlatform: text('source_platform'),
    sourceLocation: text('source_location'),
    purchaseDate: timestamp('purchase_date', { withTimezone: true }),
    // Costs
    costPrice: numeric('cost_price', { precision: 12, scale: 2 }).notNull(),
    shippingInCost: numeric('shipping_in_cost', { precision: 12, scale: 2 }),
    otherCosts: numeric('other_costs', { precision: 12, scale: 2 }),
    // Listing
    listedPrice: numeric('listed_price', { precision: 12, scale: 2 }),
    listedAt: timestamp('listed_at', { withTimezone: true }),
    listedPlatform: platformEnum('listed_platform'),
    externalListingId: text('external_listing_id'),
    // Sale
    status: itemStatusEnum('status').notNull().default('IN_STOCK'),
    soldAt: timestamp('sold_at', { withTimezone: true }),
    soldPrice: numeric('sold_price', { precision: 12, scale: 2 }),
    soldPlatform: platformEnum('sold_platform'),
    buyerCountry: text('buyer_country'),
    // Sale costs
    platformFees: numeric('platform_fees', { precision: 12, scale: 2 }),
    paymentFees: numeric('payment_fees', { precision: 12, scale: 2 }),
    shippingOutCost: numeric('shipping_out_cost', { precision: 12, scale: 2 }),
    shippingCharged: numeric('shipping_charged', { precision: 12, scale: 2 }),
    refundAmount: numeric('refund_amount', { precision: 12, scale: 2 }),
    // Flags
    feeEstimated: boolean('fee_estimated').notNull().default(false),
    // Media
    imageUrls: jsonb('image_urls').$type<string[]>(),
    notes: text('notes'),
    // Audit
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => ({
    userStatusIdx: index('items_user_status').on(t.userId, t.status),
    userSoldAtIdx: index('items_user_sold_at').on(t.userId, t.soldAt),
    userListedPlatformIdx: index('items_user_listed_platform').on(t.userId, t.listedPlatform),
    userExternalIdx: uniqueIndex('items_user_platform_external_id')
      .on(t.userId, t.listedPlatform, t.externalListingId)
      .where(/* sql */ `external_listing_id IS NOT NULL`),
  }),
);

// ---------------------------------------------------------------------------
// transactions — raw rows from eBay Transaction Report (or future API import)
// ---------------------------------------------------------------------------

export const transactions = pgTable(
  'transactions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull(),
    /** Owning item (may be null when we can't match — those land in "Needs review"). */
    itemId: uuid('item_id').references(() => items.id, { onDelete: 'set null' }),
    platform: platformEnum('platform').notNull(),
    kind: transactionKindEnum('kind').notNull(),
    source: transactionSourceEnum('source').notNull(),
    /** eBay order ID (or platform equivalent). The join key. */
    externalOrderId: text('external_order_id'),
    /** eBay transaction reference. Useful for de-dupe on re-imports. */
    externalTransactionId: text('external_transaction_id'),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    /** GBP amount, signed: positive for incoming, negative for fees/refunds. */
    amount: numeric('amount', { precision: 12, scale: 2 }).notNull(),
    currency: text('currency').notNull().default('GBP'),
    /** Free-text description from the source CSV (verbatim). */
    description: text('description'),
    /** The raw parsed row for audit / re-parse purposes. */
    raw: jsonb('raw'),
    importJobId: uuid('import_job_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userOccurredIdx: index('transactions_user_occurred').on(t.userId, t.occurredAt),
    userItemIdx: index('transactions_user_item').on(t.userId, t.itemId),
    dedupeIdx: uniqueIndex('transactions_dedupe')
      .on(t.userId, t.platform, t.externalTransactionId)
      .where(/* sql */ `external_transaction_id IS NOT NULL`),
  }),
);

// ---------------------------------------------------------------------------
// import_jobs — one row per CSV upload or API sync
// ---------------------------------------------------------------------------

export const importJobs = pgTable('import_jobs', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull(),
  platform: platformEnum('platform').notNull(),
  source: transactionSourceEnum('source').notNull(),
  status: text('status').notNull().default('QUEUED'),
  /** Storage path on Supabase Storage where the raw CSV is archived. */
  rawFilePath: text('raw_file_path'),
  itemsCreated: integer('items_created').notNull().default(0),
  itemsUpdated: integer('items_updated').notNull().default(0),
  transactionsCreated: integer('transactions_created').notNull().default(0),
  rowsTotal: integer('rows_total').notNull().default(0),
  rowsUnmatched: integer('rows_unmatched').notNull().default(0),
  errors: jsonb('errors').$type<Array<{ row: number; message: string }>>(),
  startedAt: timestamp('started_at', { withTimezone: true }),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// expenses
// ---------------------------------------------------------------------------

export const expenses = pgTable(
  'expenses',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull(),
    date: timestamp('date', { withTimezone: true }).notNull(),
    category: expenseCategoryEnum('category').notNull().default('OTHER'),
    description: text('description').notNull(),
    amount: numeric('amount', { precision: 12, scale: 2 }).notNull(),
    receiptUrl: text('receipt_url'),
    taxDeductible: boolean('tax_deductible').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => ({
    userDateIdx: index('expenses_user_date').on(t.userId, t.date),
  }),
);

// ---------------------------------------------------------------------------
// tax_years — user's annual filing preferences
// ---------------------------------------------------------------------------

export const taxYears = pgTable(
  'tax_years',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull(),
    startYear: integer('start_year').notNull(),
    status: taxYearStatusEnum('status').notNull().default('OPEN'),
    /** User's chosen path. NULL = engine recommendation applies. */
    useTradingAllowance: boolean('use_trading_allowance'),
    /** Snapshot of inputs at the time the user finalised, if any. */
    snapshot: jsonb('snapshot'),
    notes: text('notes'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userYearUnique: uniqueIndex('tax_years_user_year').on(t.userId, t.startYear),
  }),
);

// ---------------------------------------------------------------------------
// audit_log
// ---------------------------------------------------------------------------

export const auditLog = pgTable(
  'audit_log',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull(),
    action: text('action').notNull(),
    entity: text('entity'),
    entityId: text('entity_id'),
    metadata: jsonb('metadata'),
    ip: text('ip'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userCreatedIdx: index('audit_user_created').on(t.userId, t.createdAt),
  }),
);

// ---------------------------------------------------------------------------
// Relations (useful for Drizzle's relational query API)
// ---------------------------------------------------------------------------

export const itemsRelations = relations(items, ({ many }) => ({
  transactions: many(transactions),
}));

export const transactionsRelations = relations(transactions, ({ one }) => ({
  item: one(items, { fields: [transactions.itemId], references: [items.id] }),
}));

// ---------------------------------------------------------------------------
// Inferred types — use these everywhere instead of redeclaring shapes.
// ---------------------------------------------------------------------------

export type Profile = typeof profiles.$inferSelect;
export type NewProfile = typeof profiles.$inferInsert;
export type Item = typeof items.$inferSelect;
export type NewItem = typeof items.$inferInsert;
export type Transaction = typeof transactions.$inferSelect;
export type NewTransaction = typeof transactions.$inferInsert;
export type Expense = typeof expenses.$inferSelect;
export type NewExpense = typeof expenses.$inferInsert;
export type TaxYearRow = typeof taxYears.$inferSelect;
export type NewTaxYearRow = typeof taxYears.$inferInsert;
export type PlatformConnection = typeof platformConnections.$inferSelect;
export type ImportJob = typeof importJobs.$inferSelect;
